[system]
name = "Calmira GNU/Linux-libre"
version = "1.2a2.1"
codename = "Aries"
description = "Calmira 1.2a2.1 GNU/Linux-libre"
arch = "x86_64" # x86_64/x86
build = 5
build_date = "none"
edition = "core" # core/extended

[maintainer]
name = "Michail Krasnov"
email = "linuxoid85@gmail.com"
years = "2021, 2022"

[resources]
organization = "https://github.com/CalmiraLinux"
master_repo = "https://github.com/CalmiraLinux/CalmiraLinux"
releases = "https://github.com/CalmiraLinux/CalmiraLinux/releases"
issues = "https://github.com/CalmiraLinux/CalmiraLinux/issues"
